### ISSUE TITLE
Permintaan Laporan Mingguan (Penyakit per wilayah dan usia)

### ISSUE THREAD

**Issue by hayuning** [tantokaya/simpus-beta#1]
Laporan mingguan penyakit ini user interface ditaruh di Operator >> laporan mingguan.
Download laporan dalam format .xls. Kira2 query nya begini nih:

SELECT
pelayanan_penyakit.kd_penyakit, icd.penyakit,
kelurahan.nm_kelurahan,
golongan_umur.gol_umur,
Count(*) AS jml
FROM
pelayanan_penyakit ,
pelayanan ,
pasien ,
kelurahan ,
golongan_umur ,
icd
WHERE
pelayanan_penyakit.kd_trans_pelayanan = pelayanan.kd_trans_pelayanan AND
(pelayanan.tgl_pelayanan BETWEEN '2015-04-01' AND '2015-04-30') AND
pelayanan.kd_rekam_medis = pasien.kd_rekam_medis AND
pasien.kd_kelurahan = kelurahan.kd_kelurahan
 AND
pelayanan_penyakit.kd_gol_umur = golongan_umur.kd_gol_umur AND
icd.kd_penyakit=pelayanan_penyakit.kd_penyakit
GROUP BY
pasien.kd_kelurahan,
pelayanan_penyakit.kd_gol_umur
ORDER By pelayanan_penyakit.kd_penyakit, kelurahan.nm_kelurahan

![datawarehousing-work-flow](https://cloud.githubusercontent.com/assets/12489878/7674075/e78067ee-fd49-11e4-84f5-c0b2761730f8.jpg)

**Comment by arief74** [comment]
Kepada Adit agar ditindaklanjuti.

**Comment by adit-gudhel** [comment]
fixed.
