### ISSUE TITLE
Bagaimana jika ingin mengubah nama obat

### ISSUE THREAD

**Issue by hayuning** [tantokaya/simpus-beta#20]
Bagaimana jika ingin mengubah/edit nama obat di master obat? Apakah diperbolehkan? Siapa yang berhak mengubahnya? --> to be discussed

**Comment by tantokaya** [comment]
Saran saya, sebaiknya dinkes saja yang berhak menambah, menghapus maupun merubah nama obat supaya data master obat terjaga
