### ISSUE TITLE
Notifikasi resep baru

### ISSUE THREAD

**Issue by hayuning** [tantokaya/simpus-beta#21]
Bisa gak dibuatkan notifikasi jika ada resep baru yang muncul?

**Comment by tantokaya** [comment]
![notifikasi resep simpus](https://cloud.githubusercontent.com/assets/6816680/7787288/0597d094-022e-11e5-9dbc-ba7fa91c74fb.PNG)

50% fix, tampil notifikasi pada header dari poli setiap ada resep baru, tinggal diatur hanya akses dari apoteker yang dapat melihat notifikasinya dan dibuatkan linknya agar dapat langsung ke menu transaksi...#mandiduluudahbaunih

**Comment by tantokaya** [comment]
Alhamdulillah fix
