### ISSUE TITLE
Perbaikan fitur panggil resep

### ISSUE THREAD

**Issue by hayuning** [tantokaya/simpus-beta#22]
Tambahkan status pelayanan (sudah dilayani/belum, ada resep atau tidak) di function panggil resep di Apotek

**Comment by hayuning** [comment]
tambahan:: Untuk panggil resep, nama pasien belum terlihat pada ID Pasien/Nama pasien.

**Comment by tantokaya** [comment]
Sudah fix ya, 
![nama pasien di apotek](https://cloud.githubusercontent.com/assets/6816680/7787904/207f3f30-024e-11e5-81b5-c78b0b6ca254.PNG)
