### ISSUE TITLE
Web Service SIMPUS

### ISSUE THREAD

**Issue by hayuning** [tantokaya/simpus-beta#26]
Buatkan Web Service untuk kepentingan data warehouse.

**Comment by adit-gudhel** [comment]
coba di listing kebutuhannya mba, biar gampang buat apinya

**Comment by arief74** [comment]
Sementara qt set sesuai requirement dr Pak Saeful dkk sj dulu, sbb :

Web service json..
Utk menampilkan rekap pelayanan.. rekap jenisbpenyakit.
Rekap stok obat di puskesmas tertentu.. dan total se kota bogor..

Regards,

Arief Sartono
Pada tanggal 23 Mei 2015 16.47, "Aditya Nursyahbani" <
notifications@github.com> menulis:

**Comment by adit-gudhel** [comment]
sudah saya buat web servicenya di https://github.com/adit-gudhel/simpus-api
dokumentasinya di https://github.com/adit-gudhel/simpus-api/wiki/Simpus-REST-API-Documentation

**Comment by arief74** [comment]
Ok sy infokan ke Pak Saeful dkk. Thx Adit
Pada tanggal 26 Mei 2015 01.23, "Aditya Nursyahbani" <
notifications@github.com> menulis:
