### ISSUE TITLE
Please assign yourself to some specific issues ya temans..

### ISSUE THREAD

**Issue by hayuning** [tantokaya/simpus-beta#27]
udah ada 22 issues tuh temans, mohon bantuannya untuk assign your self ke isu2 yang pengen dikerjakan yak supaya ga double2 yang ngerjain atau malah diem2 ada isu yg ga dikerjain sm skali. Karena sminggu bsk qta terpisahkan oleh training so please manfaatkan GIT ini sbg media komunikasi qta yaa.. Aq bsk disini coba selesaikan sebisaku ya, klo temen2 pas training bs curi2 waktu bwt intip2 simpus sih syukur bgt.. Oiya abis training kan 12 hr temen2 jg diminta ke potensi tuh, so bagaimana nasib simpus inih... ga enak jeh kalo lama2 kelarnya. Update terus yak..
Thank you temans..

**Comment by arief74** [comment]
Ok Bu Hayu good job .. Sy jg mulai nyicil lap system analyst nya .. Bahan
SOAP kemrn masuk jd dua judul .. Thx
Pada tanggal 22 Mei 2015 16.06, "Hayu" notifications@github.com menulis:

**Comment by tantokaya** [comment]
Mantab bu Hayu, sekalian bantu teman-teman coding juga ya, yah yang kira kira bisa dicoding tolong di coding, kami coding sudah tanpa mengenal waktu, hari libur bahkan sampai malam kami korbankan hanya untuk coding, tenang aja meskipun besok jadwal training kami ga akan lepas tanggung jawab ga usah cemas, banyak banyak istighfar #loh, trims :)
