### ISSUE TITLE
Request Rapat tgl 21 Mei 2015 belum masuk semua

### ISSUE THREAD

**Issue by tantokaya** [tantokaya/simpus-beta#28]
Tolong kertas request yang ada 11 butir kemarin mengenai gudang dan apotek di masukan ke isu supaya bisa tahu apa yang perlu saya perbaiki, trims

**Comment by hayuning** [comment]
Udah mas smuanyaaa.. Cek satu2 di isunya yaa..
Tnang ae aq jg bsk coding mas, emg ga seahli tmn2 tp awighnamastu bisa.

**Comment by tantokaya** [comment]
okey siip
