### ISSUE TITLE
Fitur cetak Surat Rujukan

### ISSUE THREAD

**Issue by hayuning** [tantokaya/simpus-beta#4]
Format surat rujukan dari Botim sbb:
![rujukan](https://cloud.githubusercontent.com/assets/12489878/7674447/86287ae6-fd52-11e4-8245-981c8e52db9e.JPG)

**Comment by adit-gudhel** [comment]
udah di release format awal, tinggal di buat querynya untuk get data pasien

**Comment by hayuning** [comment]
Master TnT atau Bram nglanjutin mau ya?? Source udah di push k branch simpus-botim.
Adit sptnya lg 'potensi' mode on hari ini.
Fitur ini penting soalnya dan hari ini sdh hrs kelar. Bisa dibuka dengan akun pendaftaran, passwd pendaftaran, di menu pelayanan hari ini dan pilih aksi cetak rujukan.
Thank you..

**Comment by arief74** [comment]
Ok dilanjut Bram, upayakan s.d nnt malam selesai yah.  Akan dipresentasikan besok di Botim.  Trims

**Comment by hayuning** [comment]
Aq coba lanjutkan skrg pak, nti klo lost somewhere saya colek adit or sapa yg saat itu lg deket hahahhaa...

**Comment by arief74** [comment]
Awas jangan salah colek :-p
Pada tanggal 20 Mei 2015 15.10, "Hayu" notifications@github.com menulis:

**Comment by hayuning** [comment]
Done..tinggal push k sini.
