### ISSUE TITLE
Cross Checking tabel Pasien Pusk. Botim

### ISSUE THREAD

**Issue by hayuning** [tantokaya/simpus-beta#5]
Database pasien yang qta konversikan ke simpus untuk keperluan launching waktu itu adalah per 29 januari 2015. Selama feb - April sebelum launching, jumlah data pasien mereka kan bertambah. Jadi diperlukan cross check database pasien di aplikasi desktop botim untuk disesuaikan kembali dengan dbase simpus-bogortimur, karena kd_rekam_medis pasti berbeda.
Untuk pendaftaran pasien baru di simpus kd_rekam_medis kan diset otomatis ke P-000000blabla, padahal kd_rekam_media yg mereka gunakan yg ter-generate dari aplikasi desktop mereka. Butuh 1 field di tabel pasien atau cara lain untuk menampung 2 jenis kd_rekam_medis yang berbeda ini. Any solution???
Salah satu agenda untuk hari Kamis besok adalah Copy database aplikasi desktop botim ini. Ingatkan saiya kalo bsk lupa yaaak...

**Comment by arief74** [comment]
Ini kan jatuhnya pasien baru semua jadinya ya.  Saya kira perlu ditambahkan 1 (satu) field baru sebagai bagian dari tabel pasien dimana isinya adalah kode rekam medis dari aplikasi desktop ini ya.  Ini sudah sesuai dengan konsep tabel konversi kan ?

Ini juga bisa digeneralisir / dibakukan sebagai prosedur standar impor data dari sistem yang akan direplace.  Silakan dilanjut saja oleh Bram untuk kopi database pasien dari Botim dan Bu Hayu untuk tindak lanjut revisi db dan coding nya.  Trims.

**Comment by hayuning** [comment]
Hari ini saya sudah selesaikan tahap converting tabel pasien botim dari aplikasi lama ke simpus; dengan penyesuaian struktur tabel di simpus dan cross checking kd_rekam_medis karena untuk pendaftaran pasien baru selama sebulan kmrn mereka menginputkan ke simpus dan ke aplikasi lama padahal proses generate format kd_rekam_medisnya berbeda, hal ini ngaruh juga ke tabel pelayanan, so isi tabel pelayanan hari ini juga sudah disesuaikan.

Isu penting yang hrs segera diputuskan adlh mslh penomoran kd_rekam_medis ini, next nanti qta bahas di lain issue..

kesimpulan: tabel pasien dan pelayanan di pus_bogortimur sudah berubah isi dan strukturnya, plus ada penambahan 1 tabel yaitu tabel kartu_medical untuk menampung info ttg KK. Silakan tmn2 download dbase terbaru.
